package main

import (
	"note_api/utils"
	"testing"

	"github.com/golang-jwt/jwt/v4"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

func TestGenerateJWT(t *testing.T) {

	id := primitive.NewObjectID()

	mockUserData := utils.UserData{
		ID:       id,
		Username: "username_Test_123",
	}

	token, err := utils.GenerateJWT(mockUserData)

	if err != nil {
		t.Error(err.Error())
	}

	if len(token) == 0 || token == "" {
		t.Error("Token should not be empty")
	}

	keyFunc := func(token *jwt.Token) (interface{}, error) {
		return []byte("SecretYouShouldHide"), nil
	}

	decodedToken, err := jwt.Parse(token, keyFunc)

	if err != nil {
		t.Error("Unable to parse the token generated by GenerateJWT ", err.Error())
	}

	if !decodedToken.Valid {

		t.Error("The generated token is not valid")

	}

}
