on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker-compose up -d --build

    - name: Run tests
      run: |
        docker-compose exec -T api go test -v ./testing
    - name: Check test status
      run: exit $(docker-compose exec api go test -v ./testing | grep FAIL | wc -l)